# -*- coding: utf-8 -*-

version: 1

disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s - %(pathname)s - %(lineno)d - %(name)s - %(levelname)s - %(message)s"
        datefmt: "%m/%d/%Y %I:%M:%S %p"        
    error:
        format: "%(asctime)s- %(pathname)s - %(lineno)d - (levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
        datefmt: "%m/%d/%Y %I:%M:%S %p"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: error        
        mode: w
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    
    # info_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: INFO
    #     formatter: standard        
    #     mode: w
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # error_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: ERROR
    #     formatter: error        
    #     mode: w
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # debug_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: DEBUG
    #     formatter: standard
    #     mode: w
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # critical_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: CRITICAL
    #     formatter: error
    #     mode: w
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

    # warn_file_handler:
    #     class: logging.handlers.RotatingFileHandler
    #     level: WARN
    #     formatter: standard
    #     mode: w
    #     maxBytes: 10485760 # 10MB
    #     backupCount: 20
    #     encoding: utf8

root:
    level: DEBUG
    handlers: [console, file_handler]
    
loggers:
    <module>:
        level: DEBUG
        handlers:  [console, file_handler]
        propagate : False 

    <module.x>:
        level: DEBUG
        handlers: [ file_handler]
        propagate : True